CREATE TABLE categories (
  id UUID PRIMARY KEY, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL UNIQUE,
  icon VARCHAR(40) NOT NULL, item_count INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE products (
  id UUID PRIMARY KEY, category_id UUID NOT NULL REFERENCES categories(id), name VARCHAR(200) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE, description VARCHAR(1000) NOT NULL, price NUMERIC(12,2) NOT NULL,
  previous_price NUMERIC(12,2), rating NUMERIC(2,1) NOT NULL, image_url VARCHAR(1000) NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE roles (id UUID PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE);
CREATE TABLE users (id UUID PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE user_roles (user_id UUID NOT NULL REFERENCES users(id), role_id UUID NOT NULL REFERENCES roles(id), PRIMARY KEY(user_id, role_id));
CREATE TABLE inventory (product_id UUID PRIMARY KEY REFERENCES products(id), quantity INTEGER NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
