import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { AuthProvider } from './features/auth/AuthContext'; import { CartProvider } from './features/cart/CartContext';
import { HomePageDatabase } from './pages/HomePageDatabase'; import { ProductsPage } from './pages/ProductsPage'; import { ProductDetailPage } from './pages/ProductDetailPage'; import { CartPage } from './pages/CartPage'; import { CheckoutPage } from './pages/CheckoutPage'; import { AuthPage } from './pages/AuthPage'; import { ProfilePage } from './pages/ProfilePage'; import { OrderDetailPage } from './pages/OrderDetailPage'; import { AdminCategoriesPage } from './pages/AdminCategoriesPage'; import { AdminDashboardPage } from './pages/AdminDashboardPage'; import { AdminOrdersPage } from './pages/AdminOrdersPage'; import { CategoriesPage } from './pages/CategoriesPage';
import { AdminCustomersPage } from './pages/AdminCustomersPage'; import { AdminInventoryPage } from './pages/AdminInventoryPage'; import { AdminProductsPageV2 } from './pages/AdminProductsPageV2';
import './styles/index.css'; import './styles/homepage.css'; import './styles/catalog.css'; import './styles/cart.css'; import './styles/auth.css'; import './styles/profile.css'; import './styles/admin.css'; import './styles/dashboard.css';
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><AuthProvider><CartProvider><Routes>
  <Route path="/" element={<HomePageDatabase/>}/><Route path="/products" element={<ProductsPage/>}/><Route path="/categories" element={<CategoriesPage/>}/><Route path="/products/:productId" element={<ProductDetailPage/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/checkout" element={<CheckoutPage/>}/><Route path="/login" element={<AuthPage mode="login"/>}/><Route path="/register" element={<AuthPage mode="register"/>}/><Route path="/profile" element={<ProfilePage/>}/><Route path="/orders/:orderId" element={<OrderDetailPage/>}/>
  <Route path="/admin" element={<AdminDashboardPage/>}/><Route path="/admin/dashboard" element={<AdminDashboardPage/>}/><Route path="/admin/products" element={<AdminProductsPageV2/>}/><Route path="/admin/categories" element={<AdminCategoriesPage/>}/><Route path="/admin/orders" element={<AdminOrdersPage/>}/>
  <Route path="/admin/customers" element={<AdminCustomersPage/>}/><Route path="/admin/inventory" element={<AdminInventoryPage/>}/>
</Routes></CartProvider></AuthProvider></BrowserRouter></StrictMode>);
