spring:
  application:
    name: shoply-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shoply}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
server:
  error:
    include-stacktrace: never
  port: ${SERVER_PORT:8080}
shoply:
  jwt:
    secret: ${JWT_SECRET:3gWcDR89A4TPEhLZB4fkxJCCCYYGmzG0E9z+MCkX3jU=}
    expiration-hours: 24
